server:
  port: 5555
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:8161
    packages:
      trust-all: true
    pool:
      enabled: true
      max-connections: 50
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ticket_reg_info
      username: admin
      password: test
eureka:
  client:
    service-url: http://localhost:8761/eureka
