server:
  port: 7770

spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/ticket_base
    driver-class-name: org.postgresql.Driver


  flyway:
    url: jdbc:postgresql://localhost:5432/ticket_base
    user: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:8161
    packages:
      trust-all: true
    pool:
      enabled: true
      max-connections: 50

  application:
    name: business-client

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


