server:
  port: 7770

spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/ticket_base
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://localhost:5432/ticket_base
    user: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
